# Generated by Django 5.0.1 on 2024-02-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CornPest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
